version: "3"

services:
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                     C O D E I G N I T E R  v4.2.1                        #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
    codeigniter4:
        image: atsanna/codeigniter4:latest
#        image: atsanna/codeigniter4:v4.2.1-php8.1-apache
#        image: atsanna/codeigniter4:v4.2.1-php8.1.7-apache
#        image: atsanna/codeigniter4:v4.2.1-php8.0-apache
#        image: atsanna/codeigniter4:v4.2.1-php8.0.20-apache
#        image: atsanna/codeigniter4:v4.2.1-php7.4-apache
#        image: atsanna/codeigniter4:v4.2.1-php7.4.30-apache
        container_name: 'codeigniter4'
        environment:
          - REGEN_ENV_FILE=1

          - CI_ENVIRONMENT=development
          - APP_BASE_URL=http://localhost/

          - ROOT_EMAIL=renefgj@gmail.com
          - MAIL_SERVER=smtp.google.com
          - MAIL_SERVER_PORT=586
          - MAIL_SERVER_USER=${MAIL_SERVER_USER}
          - MAIL_SERVER_PASSWORD=${MAIL_SERVER_PASSWORD}
          - MAIL_SERVER_TLS=${MAIL_SERVER_TLS}
          - MAIL_SERVER_STARTTLS=${MAIL_SERVER_STARTTLS}
        ports:
          - 80:80
        links:
          - codeigniter4_mysql
        volumes:
          - /d/projeto/www/brapci3.3/:/var/www/html

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                               M Y S Q L                                  #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
    codeigniter4_mysql:
        image: mariadb
        container_name: 'codeigniter4_mysql'
        ports:
          - 3306:3306
        volumes:
          - ./localfolder/mysql:/var/lib/mysql
          - ./localfolder/logs/mysql:/var/log/mysql
        environment:
          MYSQL_ROOT_PASSWORD: 448545ct
          MYSQL_DATABASE: brapci
          MYSQL_USER: sa
          MYSQL_PASSWORD: 123456

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                         P H P M Y A D M I N                              #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
    codeigniter4_phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.2
        container_name: 'codeigniter4_phpmyadmin'
        links:
          - codeigniter4_mysql
        environment:
          PMA_HOST: codeigniter4_mysql
          PMA_PORT: 3306
        ports:
          - 81:80
        volumes:
          - ./localfolder/sessions:/sessions